# This workflow defines a process to publish a Docker image to Docker Hub

name: Publish Docker image

# This workflow can be triggered manually or on push events to the 'main' branch
on:
  workflow_dispatch: # Allow manual triggering
  push:
    branches: ['main'] # Trigger on pushes to the main branch

jobs:
  push_to_registry:
    # Job name: Push Docker image to Docker Hub
    # This job performs the tasks to build and push the image
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # Run the job on an Ubuntu runner

    steps:
      - name: Check out the repository code
        # This step checks out the code from the repository into the runner's workspace
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        # This step logs in to Docker Hub using secrets stored in GitHub Actions secrets
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags) for Docker
        # This step extracts metadata (tags and labels) for the Docker image
        # The output is stored in a step output named 'meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sharathsharath/product-review
          # This configures tags: one based on commit SHA and another named 'latest'
          tags: |
            type=sha
            type=raw,value=latest
      
      - name: Build and push Docker image
        # This step builds the Docker image using the specified context directory
        # and pushes it to Docker Hub with the extracted tags
        uses: docker/build-push-action@v6
        with:
          context: product-reviews  # Path to the directory containing the Dockerfile
          push: true                 # Push the image to Docker Hub
          tags: ${{ steps.meta.outputs.tags }}  # Use tags extracted in the previous step
